config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#index'
  resources :tracks, only: [:index, :show]
  resources :users, only: [:show]
  resources :users do
    resources :vehicles, only: [:new, :create, :show] do
      resources :laps, only: [:new, :create]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/lap.rb
class Lap < ApplicationRecord
  belongs_to :vehicle
  belongs_to :track
end

app/models/track.rb
class Track < ApplicationRecord
  has_many :laps
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  has_many :vehicles
end

app/models/vehicle.rb
class Vehicle < ApplicationRecord
  belongs_to :user
  has_many :laps
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

       def configure_permitted_parameters
            devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:driver_name, :email, :password)}
       end
end

app/controllers/laps_controller.rb
class LapsController < ApplicationController
  def new
    @lap = Lap.new
    @tracks = Track.all
  end

  def create
    @vehicle = Vehicle.find(params[:vehicle_id])
    puts "vehicle found:"
    puts @vehicle
    @lap = @vehicle.laps.create(lap_params)
    redirect_to root_path
  end

  private

  def lap_params
    params.require(:lap).permit(:lap_time_minutes, :lap_time_seconds, :lap_time_hundreds, :track_id, :date)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end
end

app/controllers/tracks_controller.rb
require 'net/http'
require 'json'

class TracksController < ApplicationController
  def index
    @tracksData = []
    @tracks = Track.all
    @tracks.each do |track|
      trackData = {}
      placeParam = "#{track.zip},#{track.country}"
      apiKey = "511ffbaf5f8b6c3e6a3c38975456fddd"
      resp = Net::HTTP.get('api.openweathermap.org',"/data/2.5/weather?APPID=#{apiKey}&zip=#{placeParam}")
      data = JSON.parse(resp)
      conditions = data['weather'][0]['main']
      tempK = data['main']['temp']
      tempF = convertKtoF(tempK)
      trackData[:name] = track.name
      trackData[:location] = "#{track.city}, #{track.state}"
      trackData[:weather] = "#{tempF}F, #{conditions}"
      trackData[:id] = track.id
      @tracksData << trackData
    end

  end

  def show
    @tableData = []
    @track = Track.find_by_id([params[:id]])
    @laps = Lap.where(["track_id = ?", @track.id])
    @laps.each do |lap|
      rowData = {}
      vehicle = Vehicle.find(lap.vehicle_id)
      user = User.find(vehicle.user_id)
      vehicleName = "#{vehicle.year} #{vehicle.make} #{vehicle.model}"
      lapTime = "#{lap.lap_time_minutes}:#{lap.lap_time_seconds.to_s.rjust(2, "0")}.#{lap.lap_time_hundreds.to_s.rjust(2, "0")}"
      puts "###############\n"
      puts vehicleName
      puts "###############\n"
      rowData[:vehicleName] = vehicleName
      rowData[:lapTime] = lapTime
      rowData[:rank] = "TBD"
      rowData[:driver] = user.driver_name
      rowData[:userId] = vehicle.user_id
      rowData[:vehicleId] = lap.vehicle_id
      @tableData << rowData
    end
  end

  def new
    @user = User.find(params[:user_id])
    if @user != current_user
      return render plain: 'Unauthorized', status: :unauthorized
    end
    @vehicle = Vehicle.new
  end

  def create
    @user = User.find(params[:user_id])
    if @user != current_user
      return render plain: 'Unauthorized', status: :unauthorized
    end
    @vehicle = current_user.vehicles.create(vehicle_params)
    redirect_to root_path
  end

  private

  def convertKtoF(temp)
    tempC = temp - 273.15
    tempF = (tempC * 9/5) + 32
    return tempF.round
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def show
    @user = User.find(params[:id])
    if @user == current_user
      @renderUserAdminButtons = true
    end
    @vehicle = Vehicle.where(["user_id = ?", params[:id]])
  end
end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
  before_action :authenticate_user!
  def new
    @user = User.find(params[:user_id])
    if @user != current_user
      return render plain: 'Unauthorized', status: :unauthorized
    end
    @vehicle = Vehicle.new
  end

  def create
    @user = User.find(params[:user_id])
    if @user != current_user
      return render plain: 'Unauthorized', status: :unauthorized
    end
    @vehicle = current_user.vehicles.create(vehicle_params)
    redirect_to root_path
  end

  def show
    @vehicle = Vehicle.find_by_id([params[:id]])
    @vehicleOwnerId = @vehicle.user_id
    puts "show vehicle activated"
    puts @vehicleOwnerId
    @user = User.find_by_id(@vehicleOwnerId)
    # @vehicle = Vehicle.find(params[:vehicle_id])
    if @user == current_user
      @renderUserAdminButtons = true
    end
  end

  private

  def vehicle_params
    params.require(:vehicle).permit(:year, :make, :model)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/laps_helper.rb
module LapsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/tracks_helper.rb
module TracksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/vehicles_helper.rb
module VehiclesHelper
end

app/views/laps/new.html.erb
<div class="container">
  <h1>Add a new lap time</h1>
  <%= simple_form_for @lap, url: user_vehicle_laps_path do |f| %>
    <div class = "row time-input">
      <%= f.input :lap_time_minutes, collection: 0..15, label: false, prompt: "minutes"%> 
      <%= f.input :lap_time_seconds, collection: 0..59, label: false, prompt: 'seconds'  %> 
      <%= f.input :lap_time_hundreds, collection: 0..99, label: false, prompt: "hundredths" %> 
    </div>
    <div class = "row">
      <%= f.input :track_id, collection: @tracks, label_method: :name, value_method: :id, label: false, prompt: "select a track"%>
    </div>
    <div class = "row">
      <%= f.input :date, label: false %> 
    </div>
    <div class = "row">
      <%= f.submit "Submit Time", class: 'btn btn-primary' %>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tracktimes</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-toggleable-md navbar-inverse bg-inverse">
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <%= link_to 'Track Times', root_path, class: 'navbar-brand' %>
      <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
        <ul class="navbar-nav">
          <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to 'My Profile', user_path(current_user.id), method: :get, class: 'nav-link'%>
            </li>
            <li class="nav-item">
              <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'nav-link'%>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to 'Sign in', new_user_session_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to 'Sign up', new_user_registration_path, class: 'nav-link' %>
            </li>
          <% end %>
        </ul>
      </div>
    </nav>

    <% if notice.present? %>
      <p class="alert alert-info"><%= notice %></p>
    <% end %>
    <% if alert.present? %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/static_pages/index.html.erb
<h1>Welcome to my app</h1>
<%= link_to 'View Tracks', tracks_path(@user), class: 'btn btn-primary' %>

app/views/tracks/index.html.erb
<h1>Select a Track</h1>

<ul>
  <% @tracksData.each do |track| %>
    <div class="col-12">
      <li><%= track[:name] %></li>
      <li><%= track[:location] %></li>
      <li><%= track[:weather] %></li>
      <%= link_to 'View Track Times', track_path(track[:id]), class: 'btn btn-primary' %>
    </div>
    <br> 
    <br> 
  <% end %>
</ul>

app/views/tracks/show.html.erb
<h1>Lap Times for 
<%= @track.name %>
</h1> 

<table class="table">
  <thead>
    <tr>
      <th scope="col">Rank</th>
      <th scope="col">Vehicle</th>
      <th scope="col">Driver</th>
      <th scope="col">Time</th>
    </tr>
  </thead>
  <tbody>
  <% @tableData.each do |rowData| %>
    <tr>
      <td><%= rowData[:rank] %></td>
      <td><%= link_to  rowData[:vehicleName], user_vehicle_path(rowData[:userId], rowData[:vehicleId]) %></td>
      <td><%= link_to rowData[:driver], user_path(rowData[:userId]) %></td>
      <td><%= rowData[:lapTime] %></td>
    </tr>
  <% end %>
  </tbody>
    <br>
    <br>
 

 

app/views/users/show.html.erb
<h1><%= @user.driver_name %>'s Cars</h1>
<%# <h1><%= @vehicle.inspect %></h1> 

<ul>
  <% @vehicle.each do |vehicle| %>
    <li><%= vehicle.year %></li>
    <li><%= vehicle.make %></li>
    <li><%= vehicle.model %></li>
    <%= link_to 'View Details', user_vehicle_path(vehicle.user_id ,vehicle.id), class: 'btn btn-primary' %>
    <br>
    <br>
  <% end %>
</ul>

<% if @renderUserAdminButtons %>
  <%= link_to 'Add a New Vehicle', new_user_vehicle_path(@user), class: 'btn btn-primary' %>
<% end %>

app/views/vehicles/new.html.erb
<h1>Add a new vehicle</h1>
<h1><% @currentUser %></h1>
<%= simple_form_for @vehicle, url: user_vehicles_path do |f| %>
  <%= f.input :year %> 
  <%= f.input :make %> 
  <%= f.input :model %> 
  <%= f.submit "Add a vehicle", class: 'btn btn-primary' %>
<% end %>

app/views/vehicles/show.html.erb
<ul>
  <li><%= @vehicle.year %></li>
  <li><%= @vehicle.make %></li>
  <li><%= @vehicle.model %></li>
</ul>

<% if @renderUserAdminButtons %>
  <%= link_to 'Enter a Lap Time', new_user_vehicle_lap_path(@user,@vehicle), class: 'btn btn-primary' %>
<% end %>